export const tagTypes = {
  auth: "Auth",
  notification: "Notification",
  school: "School",
  student: "Student",
  teacher: "Teacher",
  parent: "Parent",
  user: "User",
  payment: "Payment",
  feedback: "Feedback",
  terms: "Terms",
  exam: "Exam",
  section: "Section",
  subject: "Subject",
  level: "Level",
  class: "Class",
  classSchedule: "ClassSchedule",
  announcement: "Announcement",
  attendance: "Attendance",
  gradeSystem: "GradeSystem",
  manager: "Manager",
  conversation: "Conversation",
  subscription: "Subscription",
  allAdmin: "AllAdmin",
  adminOverview: "AdminOverview",
  profile: "Profile",
  staticContent: "StaticContent",
  assignment: "Assignment",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.notification,
  tagTypes.school,
  tagTypes.student,
  tagTypes.teacher,
  tagTypes.parent,
  tagTypes.user,
  tagTypes.payment,
  tagTypes.feedback,
  tagTypes.subject,
  tagTypes.class,
  tagTypes.level,
  tagTypes.section,
  tagTypes.classSchedule,
  tagTypes.terms,
  tagTypes.exam,
  tagTypes.announcement,
  tagTypes.attendance,
  tagTypes.gradeSystem,
  tagTypes.manager,
  tagTypes.conversation,
  tagTypes.subscription,
  tagTypes.allAdmin,
  tagTypes.adminOverview,
  tagTypes.profile,
  tagTypes.staticContent,
  tagTypes.assignment,
];
